name: Deploy to Star Server

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install modules
      run: npm install
    - name: Install git-ftp
      run: sudo apt update && sudo apt install -y git-ftp
    - name: Build
      run: ./build.sh
    - name: Deploy
      run: .github/scripts/deploy.sh
      env:
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}